CREATE DATABASE KRIA

use KRIA

CREATE TABLE Repositorio(
	RepoId INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(500) NOT NULL,
	Linguagem VARCHAR(500) NOT NULL,
	UltimaAtt DATETIME NOT NULL,
	DonoRepositorio VARCHAR(20) NOT NULL
)

CREATE TABLE Favorito(
	FavId INT PRIMARY KEY IDENTITY NOT NULL,
	RepoId INT FOREIGN KEY REFERENCES Repositorio(RepoId)
)


SELECT * FROM Repositorio

SELECT * FROM Favorito